Menagerie Peer Review
SotMSteamMods/CauldronMods pull request #719
Opened 2021-01-04 02:48 UTC by mgirman520

Viewing Apparatus is my one issue. Cards flipped while under another don't update the model.

2021-01-10 16:35 UTC, MSpekkio requested changes
Hey jake, I'm going to bounce Menagerie back to you.  So many of the tests have random and not random failures that I can't really confirm that things are working or not.

I fixed three tests that fail basically every time, and here's a short list other failing tests:
TestFeethsmarAlpha: 596196033
TestMenagerieBackEndTurnEffect: 599933554
TestMenagerieInitialFlip: 601932491, generally fails on about 60% of seeds
TestExoticSphere: -1893948577
TestMenagerieBackEnclosureLocation: -1339131868, generally fails on 50% of seeds
TestHyrianSnipe:  -1029071514
TestHiredKeeperOngoing: -379596204
TestAngryLethovore: 118349059

The CardEntersPlay Triggers were triggering on themselves entering, Lumobat for example, which is not correct, but that's as far as I got before the test failures prevented me from going any further.

2021-01-10 19:43 UTC, mgirman520 commented
Hey @MSpekkio 
I've addressed the located issues, the main fix I did was utilizing the OffToTheSide location to protect essential cards to the test.
If you come across further issues I can continue addressing them.

2021-01-12 03:50 UTC, MSpekkio approved these changes

2021-01-12 03:51 UTC, MSpekkio commented
Status: I need to do a test game and check over the deck list.

2021-01-13 03:34 UTC, MSpekkio approved these changes

2021-01-13 03:35 UTC, merged